### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EliArad** [daspinola/video-stream-sample#8]
Hi
This is not an issue but a question
for real live streaming we dont want to tell the size of the file to the player , but let him continue forever ask for chunks
Do you think it is possible?  if so , can you show how please?

**Comment by daspinola** [comment]
Did you manage to find something in the meantime?

As far as I can tell you can't do it using the method specified in this repository since it should always expect an `end`.

I have this to check for quite some time and will be doing some articles on the topic shortly, will post them here for posteriority once they're done.
